const DB=window.ROTA360, routes=DB.routes, meta=DB.meta;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>n===null||n===undefined?'n/d':(typeof n==='number'?n.toLocaleString('pt-BR',{maximumFractionDigits:2}):n);
const pct=n=>n===null||n===undefined?'n/d':fmt(n)+'%';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setView(v){$$('.view').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.getElementById(v).classList.add('active')}
$$('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function KPI(label,value,sub=''){return `<div class="card kpi"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub}</div></div>`}
function renderHeader(){ $('#updated').textContent=meta.updated; $('#period').textContent=meta.period; }
function renderKPIs(){ $('#kpis').innerHTML=
KPI('Registros',fmt(meta.records),'rotas consolidadas')+
KPI('Paradas',fmt(meta.stops_total),'documentadas')+
KPI('Pacotes',fmt(meta.packages_total),`${meta.routes_with_packages} rotas com contagem`)+
KPI('Horário completo',fmt(meta.routes_with_full_time),'rotas')+
KPI('Mediana',fmt(meta.median_productivity),'paradas/h')+
KPI('Fase 3',fmt(meta.phase3_records),'registros atuais');}
function renderOverview(){ $('#overviewText').innerHTML=`<p class="muted">A base cobre <b>${meta.period}</b>. O padrão central continua sendo a diferença entre sequência numérica e coerência territorial, agora com uma regra metodológica mais forte: separar <b>qualidade da roteirização</b> da <b>dificuldade natural da rota</b>.</p><p><span class="badge ok">24/09</span> Há rotas em que as áreas automáticas já são operacionalmente adequadas.</p><p><span class="badge ok">26/09</span> Uma área pode ser adequada e ainda exigir ordem interna diferente da numérica.</p><p><span class="badge new">27/09</span> A Fase 3 ganhou um caso com 8 áreas, zero revisitas, dispersão 3↔55 e erro de geolocalização 73–75.</p><p class="muted small">A mediana entre as ${meta.routes_with_full_time} rotas com horário completo é de <b>${fmt(meta.median_productivity)} paradas/h</b>. Compare sempre com contexto.</p>`}
function renderChart(){const arr=routes.filter(r=>r.productivity!==null&&r.productivity!==undefined),max=Math.max(...arr.map(r=>r.productivity));$('#prodChart').innerHTML=arr.map(r=>`<div class="bar" title="${esc(r.date)} • ${esc(r.location)} • ${fmt(r.productivity)} paradas/h" style="height:${Math.max(8,r.productivity/max*250)}px"><b>${fmt(r.productivity)}</b><span>${r.date.slice(0,5)}</span></div>`).join('')}
function flags(r){return (r.new?'<span class="badge new">nova</span> ':'')+(r.success_pct===100?'<span class="badge ok">100%</span> ':'')+`<span class="badge">${esc(r.phase||'')}</span>`}
function row(r,i){return `<tr class="clickable" onclick="openRoute(${i})"><td>${r.date}<br>${flags(r)}</td><td><b>${esc(r.location)}</b></td><td class="num">${fmt(r.stops)}</td><td class="num">${fmt(r.packages)}</td><td class="num">${fmt(r.productivity)}</td><td class="num">${fmt(r.km_total)}</td><td class="num">${fmt(r.failures)}</td><td class="num">${fmt(r.reorg_min)}</td><td>${esc(r.strategy)}</td></tr>`}
function table(data){return `<div class="tablewrap"><table><thead><tr><th>Data</th><th>Local</th><th class="num">Paradas</th><th class="num">Pacotes</th><th class="num">Paradas/h</th><th class="num">Km</th><th class="num">Insuc.</th><th class="num">Reorg. min</th><th>Estratégia</th></tr></thead><tbody>${data.map(x=>row(x.r,x.i)).join('')}</tbody></table></div>`}
const citySel=$('#routeCityFilter'),phaseSel=$('#routePhaseFilter'),statusSel=$('#routeStatusFilter'),search=$('#routeSearch');
function initFilters(){const locs=[...new Set(routes.map(r=>r.location))].sort();citySel.innerHTML='<option value="all">Todos os locais</option>'+locs.map(x=>`<option>${esc(x)}</option>`).join('')}
function renderRoutes(){const f=citySel.value,p=phaseSel.value,s=statusSel.value,q=search.value.toLowerCase();const d=routes.map((r,i)=>({r,i})).filter(x=>(f==='all'||x.r.location===f)&&(p==='all'||x.r.phase===p)&&(s==='all'||(s==='100'&&x.r.success_pct===100)||(s==='new'&&x.r.new))&&(!q||(x.r.location+' '+x.r.strategy+' '+x.r.analysis+' '+(x.r.evidence_key||'')).toLowerCase().includes(q)));$('#routesTable').innerHTML=table(d)}
citySel.onchange=renderRoutes;phaseSel.onchange=renderRoutes;statusSel.onchange=renderRoutes;search.oninput=renderRoutes;
function renderCities(){const groups={};routes.forEach((r,i)=>{(groups[r.location]??=[]).push({r,i})});$('#cityCards').innerHTML=Object.entries(groups).sort((a,b)=>b[1].length-a[1].length).map(([loc,a])=>{const st=a.reduce((s,x)=>s+(x.r.stops||0),0),pk=a.reduce((s,x)=>s+(x.r.packages||0),0),full=a.filter(x=>x.r.success_pct===100).length;return `<div class="card citycard" onclick='filterCity(${JSON.stringify(loc)})'><h3>${esc(loc)}</h3><div class="metricrow"><span>Registros</span><b>${a.length}</b></div><div class="metricrow"><span>Paradas</span><b>${fmt(st)}</b></div><div class="metricrow"><span>Pacotes conhecidos</span><b>${fmt(pk)}</b></div><div class="metricrow"><span>Rotas 100%</span><b>${full}</b></div></div>`}).join('')}
function filterCity(loc){setView('routes');citySel.value=loc;renderRoutes()}
function renderCases(){const dates=['09/09/2026','18/09/2026','24/09/2026','26/09/2026','27/09/2026'],cases=dates.map(d=>routes.find(r=>r.date===d)).filter(Boolean);$('#caseCards').innerHTML=cases.map(r=>`<div class="card analysis-card ${r.date==='27/09/2026'?'blue':''}">${r.new?'<span class="badge new">ANÁLISE ATUAL</span>':''}<h2 style="margin-top:8px">${r.date} — ${esc(r.location)}</h2><p>${esc(r.analysis)}</p><div class="metricrow"><span>Paradas / pacotes</span><b>${fmt(r.stops)} / ${fmt(r.packages)}</b></div><div class="metricrow"><span>Produtividade bruta</span><b>${fmt(r.productivity)} paradas/h</b></div><div class="metricrow"><span>Km registrado</span><b>${fmt(r.km_total)} km</b></div><div class="metricrow"><span>Revisitas</span><b>${fmt(r.revisits)}</b></div><div class="metricrow"><span>Sucesso</span><b>${pct(r.success_pct)}</b></div></div>`).join('')}
function renderICR(){ $('#icrList').innerHTML=DB.icr.map(x=>`<div style="margin:14px 0"><div class="metricrow"><span><b>${esc(x.name)}</b><br><small>${esc(x.desc)}</small></span><b>${x.weight}%</b></div><div class="icrbar"><i style="width:${x.weight}%"></i></div></div>`).join('') }
function renderDB(){ $('#dbTable').innerHTML=table(routes.map((r,i)=>({r,i}))) }
function openRoute(i){const r=routes[i],geo=r.evidence_key?`<div class="callout" style="margin-top:12px"><b>Evidência-chave:</b> ${esc(r.evidence_key)}</div>`:'';$('#modalContent').innerHTML=`<span class="badge">${esc(r.evidence)}</span> <span class="badge">${esc(r.phase||'')}</span>${r.new?' <span class="badge new">nova análise</span>':''}<h1>${r.date} — ${esc(r.location)}</h1><p class="muted">${esc(r.analysis)}</p>${geo}<div class="grid three" style="margin-top:14px"><div class="card"><h3>Volume</h3><p>${fmt(r.stops)} paradas<br>${fmt(r.packages)} pacotes<br>${fmt(r.commercial)} comerciais<br>${fmt(r.agencies)} agências<br>${fmt(r.rural)} rurais<br>${fmt(r.white)} rotas brancas</p></div><div class="card"><h3>Tempo</h3><p>1ª baixa: ${fmt(r.first)}<br>Última: ${fmt(r.last)}<br>Duração: ${r.duration_h?fmt(r.duration_h)+' h':'n/d'}<br>Produtividade: ${fmt(r.productivity)} paradas/h</p></div><div class="card"><h3>Execução</h3><p>Km: ${fmt(r.km_total)}<br>Base km: ${esc(r.km_scope)}<br>Insucessos finais: ${fmt(r.failures)}<br>Reorg.: ${fmt(r.reorg_min)} min<br>Revisitas: ${fmt(r.revisits)}<br>Sucesso: ${pct(r.success_pct)}</p></div></div><h3 style="margin-top:18px">Estratégia</h3><p>${esc(r.strategy)}</p>`;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')} window.closeModal=closeModal;window.openRoute=openRoute;window.filterCity=filterCity;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
renderHeader();renderKPIs();renderOverview();renderChart();initFilters();renderRoutes();renderCities();renderCases();renderICR();renderDB();